# Generated by Django 4.2.4 on 2023-11-04 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=100, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('comment', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_mailing_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='время и дата последней рассылки')),
                ('status', models.CharField(max_length=20, verbose_name='Статус попытки')),
                ('mail_server_callback', models.TextField(verbose_name='Ответ почтового сервера, если он был')),
            ],
            options={
                'verbose_name': 'Лог рассылки',
                'verbose_name_plural': 'Логи рассылки',
            },
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_theme', models.CharField(max_length=150, verbose_name='Тема')),
                ('mail_body', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Сообщение для рассылки',
                'verbose_name_plural': 'Сообщения для рассылки',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('daily', 'Раз в день'), ('weekly', 'Раз в неделю'), ('monthly', 'Раз в месяц')], max_length=10, verbose_name='Периодичность')),
                ('starting_at', models.DateTimeField(verbose_name='время и дата начала рассылки')),
                ('ending_at', models.DateTimeField(verbose_name='время и дата окончания рассылки')),
                ('last_mailing_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='время и дата последней рассылки')),
                ('next_mailing_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='время и дата следующей рассылки')),
                ('mailing_status', models.CharField(default='Создана', max_length=20, verbose_name='Статус рассылки')),
                ('clients', models.ManyToManyField(to='mailing.client')),
                ('mail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.mail')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
