# Generated by Django 4.2.4 on 2023-10-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Изображение (превью)'),
        ),
    ]
